name: Deploy
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: launch Docker-compose
        uses: appleboy/ssh-action@master
        env:
          VUE_APP_TODO_URL: ${{ secrets.VUE_APP_TODO_URL }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          BACK_END_PORT: ${{ secrets.BACK_END_PORT }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PWD: ${{ secrets.USER_PWD }}
          COOKIE_KEY: ${{ secrets.COOKIE_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: VUE_APP_TODO_URL, MONGO_URL,BACK_END_PORT,USER_EMAIL,USER_PWD,COOKIE_KEY
          script: |
            pwd
            if [ ! -d "./TO_DO" ]
            then
              git clone git@github.com:VincentBergerault/TO_DO.git
            fi
            cd TO_DO
            git pull origin main
            echo VUE_APP_TODO_URL=$VUE_APP_TODO_URL > ./front_end/.env.production
            docker-compose up -d --build --force-recreate
